# Generated by Django 5.0.3 on 2024-05-23 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('portada', models.CharField(max_length=500)),
                ('puntuacion', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.fabricantes')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videojuegos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.videojuegos')),
            ],
        ),
    ]
